pocketjoso/penthouse

README.md, lib/phantomjs/penthouse.js, package.json, penthouse.js, test/full-tests.js, test/static-server/yeoman-full.css, test/static-server/yeoman-small-expected.css, test/static-server/yeoman.html
Solves #36 and #37. Whitespace issues between my editors make for a noisy commit.
* `splitsWithIndexes` was not thought through properly, causing major bugs in critical path css generation, and is therefor reverted.
* Issue #36 now instead properly solved; the issue was missing to step `selectorsKept` when `::`selectors are encountered (as they are not tested but just simply kept in critical css).
* Added a more realistic critical path css generation test, taken from [critical's tests](https://github.com/addyosmani/critical/blob/master/test/test.js) - should prevent future bugs from getting merged in the future.
=> fix for bug introduced in 0.2.52

lib/index.js, lib/options-parser.js, lib/phantomjs/core.js, lib/phantomjs/usage.txt, penthouse.js, test/css-preformatter-test.js, test/full-tests.js, test/parser-test.js
The options-parser was erroring on relative html paths, but the error it throws was not passed on by `core.js`, unless in `debug` mode. Instead the feedback was just the usage string, which was very confusing. In current master such relative html paths were just let through and worked fine. (I was never aware of this until now though).
To conclude: If the options parser is going to stop execution on errors that can't be easily understood via the usage string produced by `core.js`, then the logic needs to be changed so that core displays those errors. For now, as the invalid url guard disappears, no change in core is needed.
=> fix: options parser fixes

bin/penthouse
Want to be able to handle `penthouse -v`, not sure this is the right way. cc @fatso83 .
=> add version argument to CLI

lib/phantomjs/core.js
This PR implements the solution 2 in #58 
Pro: will work with phantomjs core v1.9.8, so it works with latest nodejs wrapper (currently at v1.9.17).
Con: hopefully no one will need to debug phantom exit output.
It works consistently on my repo, let's see if I broke any travis tests...
=> Wrap phantom exit in setTimeout

lib/index.js
Fix for known phantomjs security errors going to `stdout`, resolves #58 and related issues.
Not the best way to solve this, but again these problems should disappear in `phantomjs 2`. Solution pretty much copied from [criticalCSS](https://github.com/filamentgroup/criticalCSS/blob/master/critical.js#L61-L64).
=> silence known phantomjs stdout security errors

lib/phantomjs/core.js, test/basic-tests.js, test/static-server/special-chars.css
The presence of certain non ASCII characters in the `css` passed to `Penthouse` cause `Phantomjs` to hang forever (on the serialization of params?) in `Page.evaluate`. This fixes that by escaping the css before calling Phantom.
=> Fix non ascii crashes

README.md, lib/index.js, lib/phantomjs/core.js, test/core-tests.js, test/static-server/forceInclude.css
For #61.
Node module now takes an array of selectors that will not be removed even if they don't appear in the critical viewport:
``` 
penthouse({
...
forceInclude: [ '.myLoggedInSelector', '.andFriends', /^\.andRegexToo.*/ ] 
});
```
=> Force include 

lib/phantomjs/core.js, lib/phantomjs/non-matching-media-query-remover.js, package.json, test/core-tests.js, test/static-server/non-matching-mq--remove.css, test/static-server/yeoman-medium--expected.css
`print` media queries were already removed, now `Penthouse` also removes and `min-width` / `min-height` media query that exceeds the defined viewport size (1300x900 by default).
Resolves #67.
=> Remove unmatched media queries

lib/phantomjs/core.js
the first render happens before these requests resolve, so just wasteful to execute them.
If necessary can provide an option for this in the future, to override these request abortions, perhaps via regex or string matching.
=> abort js requests

lib/phantomjs/non-matching-media-query-remover.js, test/basic-tests.js, test/static-server/invalid-media.css
Since #88 and the introduction of https://github.com/ericf/css-mediaquery in penthouse certain invalid media queries has caused penthouse to hang - this fixes that.
=> Handle invalid media queries

lib/index.js
The timeout keeps an open handle and therefore delays ending the process
=> clear timeout on exit

lib/phantomjs/core.js, package.json
Added `apartment` to remove `animation` and `transition`, including all vendor prefixes and destructured properties.
I was wondering if we could benefit from adding an option that removes a few more properties that don't really affect layouting and could further reduce byte size:
- `::selection`
- `text-shadow`
- `box-shadow`
- `border-radius` properties with `px` values under `50px`
- `pointer-events`
- `cursor` if we want to be super aggressive
- I'm sure there's others
=> Remove unused CSS properties

lib/index.js, package.json, test/static-server/yeoman-medium--expected.css
Re-introduces non critical prop removal as introduced in #100 by @bevacqua. (Was previously reverted as unfortunately latest version of `css` library, which `apartment` uses, cant be used in `phantom`. Now moved outside of phantomjs script.)
Added `user-select` and `tap-highlight-color` to list of props to remove.
=> Post rm props

lib/index.js
process event listeners were never cleared explicitly
(only by the parent process exiting), which meant that in long living
node processes all variables in scope were retained forever.
=> fix memory leaks

README.md, lib/index.js
Allows for passing an additional set of options for phantomjs:
```js
penthouse({
...
phantomJsOptions: { // see `phantomjs --help` for the list of all available options
'proxy': 'http://proxy.company.com:8080',
'ssl-protocol': 'SSLv3'
}
}, ...)
```
=> Closes #111: allow for configuring phantomjs

lib/phantomjs/core.js, test/static-server/yeoman-full--invalid.css
Drastic improvement, execution time saving of about 80% for _invalid_ css files! 💥 
Did some profiling and found that the function for returning css selector case to original after getting it back in lower base via the browser in the css normalisation handling takes an enormous amount of time to run, f.e. 40/48s for a 1.2MB example css file I was running with.
.. so disabling it for now.
If wanting to bring it back in the future: put it _outside_ of page.evaluate loops, and profile!  But first make sure it's actually needed, not sure I got that right last time.
--
Also added profiling logs to Penthouse, now spitted out to stdout.
=> Normalising perf improvements

lib/index.js, lib/phantomjs/core.js, package.json, test/core-tests.js, test/normalising-css-tests.js, test/static-server/escaped-hex-reference-in-invalid.css
`Content: ''"` for font icons and other special characters were getting lost through normalization process (when css has errors), due to lack of escaping. This leas to font-icons never rendering with critical css, even if font was loaded.
This should fix that, although the fix is not super clean, and probably doesn't cover all cases. The important bit is very popular font icons, which should work now, even it the css has (other) errors.
=> Fix fonticons in normalise

README.md
The example within the README had invalid syntax and would not run.
The version proposed within this PR does run and outputs expected CSS.
=> Add a working example to the README

lib/index.js, package.json
Currently penthouse is not working on windows due to the hard-coded `/tmp` directory.
See: https://github.com/addyosmani/critical/issues/149
=> use os independent tmp directory

package.json
@pocketjoso: there seems to be more dev deps unused like express, morgan and portfinder. Should I remove those too?
=> Remove unused devDependencies and normalize package.json

lib/index.js
Apparently there is some css syntax that the `css.parse` method finds illegal that comes through the normalisation step, which caused an uncaught error to be thrown. This error is now caught instead. (except for in `strict` mode - where normalisation is not attempted at all).
=> prevent css parse to throw on errors after normalising

lib/phantomjs/normalize-css.js
for some reason the 'format("woff")' parts of @font-face src declarations
come back without the quotes, which makes them invalid,
and causing the font-face to not work, at least not in some browsers
(latest Chrome f.e.).
To circumvent this, re-apply the missing quotes.
=> quote font-face format values in normalized css

README.md, lib/index.js, lib/phantomjs/core.js
Add blockJSRequests option (default = true).
Makes it possible to load JS files. See discussion here: https://github.com/pocketjoso/penthouse/issues/113
Made it optional. Choice = good, even if it might be wasteful :)
=> Optional unblock js requests

package.json
to ensure it gets downloaded via npm install.
Should resolve #142.
=> list phantomjs config in files in package.json

package.json
The used tmp library in version 0.0.28 has at least one critical bug in it, updating it solves everything like:
ReferenceError: c is not defined
at _removeCallback (/var/app/current/node_modules/penthouse/node_modules/tmp/lib/tmp.js:355:47)
at Object._cleanupCallback [as removeCallback] (/var/app/current/node_modules/penthouse/node_modules/tmp/lib/tmp.js:409:5)
at ChildProcess. (/var/app/current/node_modules/penthouse/lib/index.js:186:17)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
at Process.onexit (/var/app/current/node_modules/async-listener/glue.js:188:31)
=> Update 'tmp' in package.json

package.json
Had some issues sometime after the 0.11.0 update because babel-polyfill couldn't be found. Should just need to be moved from dev deps to regular deps.
Let me know if I'm mistaken or missed anything.
=> Make babel-polyfill Regular Dependency

.eslintrc, lib/index.js, package.json, src/index.js, yarn.lock
So, for kicks and giggles I was trying out Node 8.0 on my machine (I know, I know… it's not even LTS yet), but found that everything was working fine with my build system except for penthouse. So dug in and found that the only issue was babel-polyfill seemingly not working, and that since really the only reason it was (apparently) being pulled in for was `regeneratorRuntime`, using the regenerator-runtime was an easy fix.
It also has the added bonus of being much lighter weight, since you don't have to pull in all of the extra polyfill stuff. And as an added bonus, you look to be set for Node 8.0 with this change.
Also, was having some issues with my own .eslintrc rules bubbling up into the prettier-standard call and adding semicolons to everything—so also added a local .eslintrc file …
=> Replace babel-polyfill with regenerator-runtime

lib/phantomjs/core.js, src/phantomjs/core.js, test/core-tests.js, test/node-module-tests.js
I was looking into a case where Penthouse execution took around 90s, which is way out of the ordinary, and found some really neat perf improvements ✨  - bringing the same case down to 6s execution time (15x faster) 💪. A well linted, slim css file will not be effected much. 
The bottleneck was getBoundingClientRect calls, in particular to elements taking up a large screen estate, like `body` and selectors like `.page-container`. In some cases I saw individually getBoundingClientRect calls taking over 500ms, which quickly piled up in a large css file.
- never query the DOM for `html` and `body` selectors, since they are always "above the fold"
- cache `isAboveFold` computations per element.
- given the new cache, penthouse calls will now consume more memory. I haven't seen anything worth …
=> Perf improvents

package.json
Otherwise, it triggers the error
```
$ yarn install
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Refusing to download the git repo {"hostname":"github.com","protocol":"https:","repository":"https://github.com/pocketjoso/css.git"} over HTTPS without a commit hash - possible certificate error?
```
=> Specify a branch for pocketjoso/css to fix yarn

src/index.js, src/phantomjs/core.js, test/core-tests.js
They were previously ignored, meaning that you couldn't f.e. ignore case (`/something/i`). Now fixed.
=> Support forceinclude regex flags

README.md, package.json, yarn.lock
* `README.md` has a small typo in the example (an extra `},`, not needed 😉 ).
* The fact that the project uses `puppeteer` is awesome. However, because it is pointing to Google's github repo it gets the master and does not run the build to be compliant with Node 6, which causes the following error:
* Fixes the typo on the `README.md`'s example.
* Changes the `package.json` to point to the (currently latest) puppeteer's package version instead of its repo. Also changes the `yarn.lock` to point to the correct version. Both steps done via `yarn add puppeteer` as @pocketjoso suggested. 
Note: this is my first PR in this repo, all feedback about contribution procedures (but not only) is more than welcome 👍
=> Changes package.json to point to Puppeteer's package instead of repo. Also fixes typo on README.md

src/core.js, test/node-module-tests.js, test/util/chromeProcessesRunning.js
Pages that had some error f.e. when failed to be opened where never closed, leading to these extra chrome processes hogging extra resources and essentially acting as a memory leak (although outside of the Node process).
=> Fix bug causing chrome page to not be closed

src/index.js
Bug: trying to set `blockJSRequests` as false fails, unwanted behavior: fallback to the default value (true).
=> fixed options.blockJSRequests always getting default value (true)

README.md, src/non-matching-media-query-remover.js, test/post-formatting-tests.js
given that Penthouse works very well to generate only one critical css file
per page (as opposed to different ones for different viewport sizes),
and that this is what I recommend - it makes sense to allow to keep larger
media queries so truly make the critical css work for all sizes.
`keepLargerMediaQueries enables this behavior`. The default value is set to `false`,
to be backwards compatible.
=> add keepLargerMediaQueries option

README.md, src/index.js, test/basic-tests.js
Checking if `puppeteer.getBrowser` function is passed in props to use it for launching browser instead, closes #198.
=> Support passing puppeteer browser in options

README.md, package.json, src/core.js, src/index.js, src/normalize-css.js
Uses debugjs for debugging, the same as puppeteer is using, this allows
for easier debugging, in a way that's similar with puppeteer. Also document this change.
Here is a preview from powershell:
Note:
Example could also be `env DEBUG="penthouse*" node script.js` but I feel the other is easier to understand. We could also scope everything in `index.js` to `penthouse:index` then `env DEBUG="penthouse:*" node script.js` would work fine.
=>  Use debugjs for debugging

src/core.js, src/postformatting/index.js, src/postformatting/unused-fontface-remover.js, test/post-formatting-tests.js, test/static-server/fontface--remove--expected.css, test/static-server/fontface--remove.css
improves the rest of the postformatting so that none of it operates on a css string, but instead always on the ast format - in my preliminary tests that should be faster. It could be made even faster by doing all the transformations in a single iteration, instead of once per postformatting process, but that's for the future (if it's even worth it, would have to do some more specific measurements first; normally now these operations are very fast..)
=> All postformatting done on ast

package.json, yarn.lock
I noticed that one of my projects where I use penthouse pulled in a lot more dependencies, this was due to penthouse depending on Jest. I assume this project only depends on Jest in development/testing?
Feel free to close this PR if this is not the case.
=> Move Jest to devDependencies

src/browser-sandbox/pruneNonCriticalSelectors.js, src/core.js, src/index.js
mostly has an impact when taking before/after screenshots, and when the page load is not being the bottle neck. In my production tests the latter is most often the bottle neck however, so hence why this code is better in theory, in practice it does not make much of a difference. I think it is slightly cleaner though.
=> improve parallelization by minimizing await usage

package.json, src/core.js, yarn.lock
cannot go to latest version (1.1.1 at time of writing this)
because it reintroduces the `file://` protocol bug that 1.0.0 fixes:
https://github.com/GoogleChrome/puppeteer/issues/1506#issuecomment-371227988
=> puppeteer@1.0.0

src/index.js
Without this check, several browser instances are created. It leads to the process hanging.
=> Do not recreate browser instance if getBrowser options passed

package.json, src/core.js, src/index.js, src/non-matching-media-query-remover.js, src/postformatting/embedded-base64-remover.js, src/selectors-profile.js
if a grid parent using grid-template-areas is critical (f.e. the body), thus appearing in the critical css, direct children who are supposed to be placed correctly via grid-area (f.e. as a page footer) can appear incorrectly in the critical viewport if they are not also included. This change essentially force includes them.
Fixes cases where the critical css produced incorrect results.
Ths will make critical css files larger, in vain for most users, and it takes some time to make these extra checks.
I'm currently testing this change to determine the exact extent of the increase in time and size. If too bad, I will consider an alternative solution.
-------
This PR also reverts a change to include `--disable-dev-shm-usage` launch flag to puppeteer, which [is recommended for …
=> Keep rules with grid-area property

src/core.js, test/core.test.js, test/static-server/infinite-page-refresh.html
Resolves https://github.com/pocketjoso/penthouse/issues/263
Now Penthouse will thrown an if the page unloads (is navigated away from) during critical css generation. The error is:
> PAGE_UNLOADED_DURING_EXECUTION: Critical css generation script could not be executed.
>
> This most often happens when the page is navigated away from after load, f.e. window.location or via a meta tag refresh directive. For the critical css generation to work the loaded page must stay: remove any redirects or move them to the server. You can also disable them on your end just for the critical css generation, f.e. via a query parameter.
=> Page unloaded explicit handling

examples/custom-browser.js, package.json, src/core.js, src/index.js, test/basic.test.js, test/run-sequential/node-module.test.js, yarn.lock
Upgrading dependencies.
With Puppeteer 1.7 came the possibility to set the defaultViewport on the browser, which penthouse now uses to avoid some work (when multiple jobs are run in parallel with the same width+height settings). Added a test case to ensure the viewport is still updated properly (was never broken, but new logic required with this change).
=> Puppeteer 1.7, default viewport

src/browser.js, src/core.js
Since Penthouse@1.8 there has been more penthouse timeouts. I traced this puppeteer never firing the load event for sites with https errors. Eventually I got a tip on a workaround for this (https://github.com/GoogleChrome/puppeteer/issues/3118#issuecomment-417754246), so should work better now. This workaround should also resolve the blocker for upgrading puppeteer (to 1.7), but I will test that later - one thing at the time.
=> Timeout fixes

src/browser.js, src/index.js
The previous logic could lead to race conditions; the browser instance a later penthouse call was relying on could be closed by an earlier penthouse execution. This PR fixes that. This logic has had bugs before in certain edge cases so I will leave this PR open for a while and do further tests before merging. I will publish a release candidate of it.
=> internal job counter determining if should close browser

README.md, src/core.js, src/index.js, test/basic.test.js
Penthouse isn't stopping nor is throwing an error when the server is responding with an error status code. With this change only 200-299 response status codes will let penthouse proceed.
=> #284: throw an error on server error response

README.md, src/core.js, src/index.js, src/selectors-profile.js, test/core.test.js, test/static-server/forceExclude.css
https://github.com/pocketjoso/penthouse/issues/243
Signed-off-by: Andreas Schnederle-Wagner <schnederle@futureweb.at>
=> Added forceExclude

src/non-matching-media-query-remover.js, test/pre-formatting.test.js
This PR allows penthouse to correctly keep or discard media queries bracketing a viewport interval, i.e. `@media (min-width: 320px) and (max-width: 650px)`.
Previously these MQs would be included in the css output even when not matching, regardless of the setting of `keepLargerMediaQueries`. For example, running penthouse at 650px would include a media query devised for tablets `(min-width: 768px) and (max-width: 1023px)`.
We improved the logic that tests whether to keep or drop a media query by adding an explicit test for media queries using the AND operator. We also rewrote the logic for keepLargerMediaQueries by testing both against the current viewport size and the LLVP  (Ludicrously Large ViewPort) and keeping whatever is true.
All new logic is tested in `pre-formatting.test.js` …
=> Properly test min-max media queries for critical CSS inclusion

src/browser.js
if using a custom browser, getBrowser is not called when "browser" is != null. As the behaviour of the browser instance is controlled outside, this leads to situation where a browser is closed, but penthouse believes the browser is still running.
=> fix(browser): when usingCustomGetBrowser is set, call getBrowser each time 

src/core.js
👋 Hey!
I was going over a bug today related to URL interception and noticed that there's a bug in `test(interceptedRequest.url)` because `url` actually is going to return the function. To get the URL string the function should be called.
Here's an example from puppeteer documentation:
https://github.com/puppeteer/puppeteer/blob/main/new-docs/puppeteer.page.md#example-2
=> interceptedRequest.url should be a function call
