pocketjoso/penthouse

README.md
lib/index.js
lib/options-parser.js
lib/phantomjs/core.js
penthouse.js
test/basic-tests.js
test/full-tests.js
test/parser-test.js
test/static-server/at-rule-case-1--remain.css
test/static-server/at-rule-case-2--remove.css
test/static-server/at-rule-case-4--remove.css
test/static-server/yeoman-full.css
test/static-server/yeoman-small-expected.css
test/static-server/yeoman.html

Preparing the `dev` branch to be merged with `master`. As proposed in #41, the multi url handling previously added to `Penthouse` has now been removed. All other improvements on the `dev` branch will stay.
Tests have been updated.

dev: next without multi url

---

lib/index.js
lib/options-parser.js
lib/phantomjs/core.js
lib/phantomjs/usage.txt
penthouse.js
test/css-preformatter-test.js
test/full-tests.js
test/parser-test.js

Fixes for logging parsing errors 

---

lib/phantomjs/core.js
package.json
test/static-server/at-rule-case-3--remain.css

handle @-moz-document

---

test/full-tests.js
test/static-server/yeoman-medium--expected.css

more reasonable yeoman test

---

.travis.yml

Prevents duplication of core tests, for faster CI build.

custom travis test script

---

package.json

Phantomjs2

---

README.md
lib/index.js
lib/phantomjs/core.js

Added the 'userAgent' option for specifying the user agent that phantom.js should use when loading the page. "Fixes" #76

add user agent option

---

lib/index.js
lib/phantomjs/core.js
lib/phantomjs/unused-keyframe-remover.js
test/core-tests.js
test/post-formatting-tests.js
test/static-server/at-rule-case-1--remain.css
test/static-server/at-rule-case-4--remove.css
test/static-server/unused-keyframes--expected.css
test/static-server/unused-keyframes.css
test/util/normaliseCssAst.js

Keep critical keyframes rules

---

.gitignore
.jshintignore
.jshintrc
lib/index.js
lib/normalize-css.js
lib/phantomjs/.jshintrc
lib/phantomjs/core.js
lib/phantomjs/non-matching-media-query-remover.js
lib/phantomjs/normalize-css.js
lib/postformatting/embedded-base64-remover.js
lib/postformatting/index.js
lib/postformatting/unused-fontface-remover.js
lib/postformatting/unused-keyframe-remover.js
package.json
test/.jshintrc
test/basic-tests.js
test/core-tests.js
test/node-module-tests.js
test/normalising-css-tests.js
test/post-formatting-tests.js
test/static-server/app.js
test/util/compareScreenshots.js
test/util/normaliseCssAst.js

@pocketjoso: I went with the rules you already used, just removed any deprecated ones and tweaked the rest.
Let me know your thoughts and I'll rebase the branch to address any issues.

Add JSHint support

---

README.md
lib/index.js
lib/phantomjs/core.js

Certain compression issues in PhantomJS can be resolved by setting:
```js
page.customHeaders = {
"Accept-Encoding": "identity"
};
```
This PR enables that:
```
customPageHeaders: {
'Accept-Encoding': 'identity' // add if getting compression errors like 'Data corrupted'
}
```
Found via:
https://github.com/ariya/phantomjs/issues/10930#issuecomment-81541618

Custom page header option

---

.travis.yml

Should test the min node version required

Test node 6

---

package.json
src/browser-sandbox/pruneNonCriticalCss.js
src/postformatting/embedded-base64-remover.js
src/postformatting/index.js
src/postformatting/unwanted-properties-remover.js
test/core-tests.js
test/post-formatting-tests.js
test/static-server/psuedo--remain.css
test/static-server/psuedo--remove.css
test/static-server/rm-non-critical-selectors--expected.css
test/static-server/yeoman-medium--expected.css
yarn.lock

Now the full processing pipeline in Penthouse is fault tolerant.
~~Update: also improved the rest of the postformatting so that none of it operates on a css string, but instead always on the ast format - in my preliminary tests that should be faster. It could be made even faster by doing all the transformations in a single iteration, instead of once per postformatting process, but that's for the future (if it's even worth it, would have to do some more specific measurements first; normally now these operations are very fast..)~~ Moved this to separate PR: #217

Properties to remove: remove (non fault tolerant) dependency

---

src/browser-sandbox/pruneNonCriticalSelectors.js
src/core.js
src/index.js
src/selectors-profile.js

Following #222, this PR parallelize some of the more expensive operations in penthouse, reducing execution time further. Will run some larger tests in my projects and report on average savings vs master.

Further perf improvements

---

.gitignore
src/core.js

from PR:
https://github.com/pocketjoso/penthouse/pull/227
by @hummal

cherry-picked improved error handling

---

package.json
test/run-sequential/perf.test.js
yarn.lock

chromium fixed bug causing file:// protocol to not be properly supported, and fix now in Puppeteer, so this updated to the latest version, `puppeteer@1.4.0` 🎉 
Also upgraded other deps.

Puppeteer latest

---

src/browser.js
src/core.js
src/index.js

just opening PR for greater visibility in case there is a regression.

fix linting, rm some wrapping promises

---

src/non-matching-media-query-remover.js
test/pre-formatting.test.js

Resolves issues with handling inversed media queries like the one in #195

Change how inversed media queries are handled

---

package.json

Bump puppeteer

---

src/postformatting/unused-fontface-remover.js
test/post-formatting.test.js
test/static-server/case-sensitive.html

Fix font family case insensitive

---

src/core.js

fix: check viewport

---

src/core.js
src/index.js

sometimes it happens that viewport or interception for allowJS fails, this reuslts into an uncaughtexception. this fixes it

fix uncaughtException
